name = "ReverseADNLSModels"
uuid = "1cd4cf3a-ab95-428b-afc2-fde2104d3d9d"
authors = ["Dominique Orban <dominique.orban@gmail.com>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[compat]
ForwardDiff = "0.10"
NLPModels = "0.15, 0.16, 0.17, 0.18"
ReverseDiff = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]